name = "github_stats"
version = "1.0.0"
description = "Example Gleam service that wraps the GitHub API, with http_server_mock integration tests"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_http   = ">= 4.3.0 and < 5.0.0"
gleam_httpc  = ">= 5.0.0 and < 6.0.0"
gleam_json   = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit                = ">= 1.0.0 and < 2.0.0"
http_server_mock        = { path = "../../http_server_mock_core" }
http_server_mock_erlang = { path = "../../http_server_mock_erlang" }
